/*
 * ================================================================
 *
 * Filename:    scoped_timer.h
 *
 * Description: RAII scope timer. The constructor starts the clock;
 *              the destructor stops it and reports.
 *
 * Created:     2026-08-29
 * EID:         iud58
 * Email:       ishdeshpa@utexas.edu
 * Author:      IshDeshpa (Ishan Deshpande)
 * Provenance:  I certify that all code contained herein is mine
 *              alone except where otherwise noted.
 *
 * ================================================================
 */

/*
 * ECE 379K -- Lab 0, Part A
 *
 * Fill in the three member functions marked TODO below. Header-only is
 * fine; there is no scoped_timer.cpp unless you want one.
 *
 * REQUIRED OUTPUT, on stderr, one line per destroyed timer:
 *
 *     [ScopedTimer] vector fill: 12.345 ms
 *
 * Exactly three digits after the decimal point. The autograder parses
 * this line, so match it character for character.
 */

#ifndef SCOPED_TIMER_H
#define SCOPED_TIMER_H

#include <chrono>
#include <cstdio>
#include <string>
#include <utility>

class ScopedTimer {
public:
    explicit ScopedTimer(std::string label)
        : label_(std::move(label)),
          start_(std::chrono::steady_clock::now()) {
    }

    ~ScopedTimer() {
        std::fprintf(stderr, "[ScopedTimer] %s: %2.3f ms\n\r", label_.c_str(), elapsed_ms());
        std::fflush(stderr);
    }

    /* Do NOT remove these. Part of the graded design -- and the writeup
       asks you what would go wrong if a ScopedTimer could be copied. */
    ScopedTimer(const ScopedTimer&) = delete;
    ScopedTimer& operator=(const ScopedTimer&) = delete;

    /* Milliseconds since construction. Must work while the object is
       still alive, i.e. before the destructor runs. */
    double elapsed_ms() const {
        using namespace std::chrono;
        
        /* Following line was generated by the AI tool Codex.
        The purpose of this code is to cast the duration of the timer 
        to a milliseconds duration, then return as a double. */
        return duration<double, std::milli>(steady_clock::now() - start_).count();
    }

private:
    std::string label_;
    std::chrono::steady_clock::time_point start_;
};

#endif  /* SCOPED_TIMER_H */
